// Global using directives

global using System.Net.Http.Json;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Blazored.LocalStorage;
global using BlazorNotiflix;
global using DotNet8.BankingManagementSystem.Frontend;
global using DotNet8.BankingManagementSystem.Frontend.Services;
global using DotNet8.BankingManagementSystem.Frontend.Features;
global using DotNet8.BankingManagementSystem.Models;
global using DotNet8.BankingManagementSystem.Models.Account;
global using DotNet8.BankingManagementSystem.Models.AdminUser;
global using DotNet8.BankingManagementSystem.Models.Bank;
global using DotNet8.BankingManagementSystem.Models.Branch;
global using DotNet8.BankingManagementSystem.Models.State;
global using DotNet8.BankingManagementSystem.Models.TownShip;
global using DotNet8.BankingManagementSystem.Models.TransactionHistory;
global using DotNet8.BankingManagementSystem.Models.Transfer;
global using DotNet8.BankingManagementSystem.Models.Users;
global using DotNet8.BankingManagementSystem.Database.EfAppDbContextModels;
global using DotNet8.BankingManagementSystem.Mapper;
global using DotNet8.BankingManagementSystem.Shared;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.JSInterop;